language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate && metricly package lint
notifications:
  slack:
    secure: FLiuYQa7s50mYWnZxl7zxCZyIZ+mTTHQTuUTjFQEyRP2SZElkFoZgqSuWiCADF/pkxLVeH0RqgSSR8C1soGmm4E+fm50Newc1gEwu5sryD2yoHrNDuaTqK16OaH0RSJTmJSbu/T6F4jm3nw3OWQpn7oNoJXjOKinyklAFqtPD27y7RLUMQu7i42TKafHljBcWZ9c8FrPQsqXIpB1zFEQDox8Kt+ti3y7YpL7qb896YAGcikgMAPiLcq5vQin8JRmLakaiqOmKSjFWRGdgPsNEZed+YLbEdoklOfYt30j4ab/JGiCoDQUB48U3s7lnnX0txpK7i0dfO9PkVuevY5teB6gveUDagLG90UJ4+32JbItPwZjVsMeahOFXrff17nadrw8gkKDS4gMWlv7fJjK1+l0NjGzpR8SHt3QkeaDMrTZjDqEMGizQyG5Ti/jC8Eb+RAzu0MKkOlWmqbRB7vK1yZr4t+HVzK5E+OMfvhTeQbZzZWPkAg4MT75gq+b+EGyS7zsslhiw95yPJecmKRnvL6V7nJSwQ+bPAWi2iHeDutuKRzn6BQa4ePS7EJ/zdFkInMMuqHxAfptsTkQEejmep5k/XPSJpeCsqi+U8uZjmlMMDrPTczbphCqAxwa5zm5hg8ff+jhEeKM1iY8ikZxHW+1FoXjK22+C8bSf44r/go=
